### ISSUE TITLE
When using seneca-user with this datastore the db schema is not generated automatically

### ISSUE THREAD

**Issue by sorin7486** [mirceaalexandru/seneca-mysql-store#13]
I tried using this data store with seneca-user and seneca-auth but it looks like I have to create the DB schema manually because this is not done from the code. This problem is made worst by the fact that it is not immediately clear what the schema should look like just from looking at the saved entities in a NOSQL store (like Mongo DB).

One solution would be to provide ANSI SQL scripts for each plugin that might need them. Another option would be to change this plugin so that it works with the others and takes care of this on its own.

**Comment by mirceaalexandru** [comment]
I think that this is not the concern of this module. I think that seneca-user must specify that in case of relational DB the structure should follow certain guidelines, eventually provide SQL scripts for major relation DB.

Otherwise we will have here SQL scripts for all plugins, similar in other relational DB plugins. It will be very hard to maintain this in case that one plugin changes the required structure.

The structure specifications should be part of the documentation from the plugin that needs that structure.

**Comment by guyellis** [comment]
@mirceaalexandru That's exactly what I was thinking as well. The SQL script for each DB in each plugin will be very similar and can be copied and tweaked in that plugin.

@sorin7486 Can you create 2 issues, one in each of seneca-user and seneca-auth, requesting a SQL script for creating the appropriate table in MySQL?

I'm going to close this but feel free to comment if you think that there's more to it in this module than @mirceaalexandru and I have mentioned. Thanks.

**Comment by sorin7486** [comment]
@guyellis There's already an issue for seneca-user, I added a comment there. I do agree that this module does not need to know the schema of other modules that might use it, but I was thinking of something more generic. For example the DynamoDB store uses a prototype: it generates the schema from the first object that is saved in it. Although this happens in the DynamoDB driver not in the seneca-module.

In any case, DynamoDB doesn't work either so I'll be opening another issue for it, probably on seneca-user. Honestly I think the datastore API needs to be a bit more robust/clear than this.

**Comment by faceleg** [comment]
I agree there should be a solution for this. I'm using seneca+sequelize in my project because I simply don't want to declare my entities both in-code and in-database.
